"""empty message

Revision ID: 231017d27899
Revises: 71d643e87c36
Create Date: 2020-04-13 13:15:17.620737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231017d27899'
down_revision = '71d643e87c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_key', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.String(length=128), nullable=True),
    sa.Column('name_first', sa.String(length=128), nullable=True),
    sa.Column('name_last', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Customer_ext_key'), 'Customer', ['ext_key'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('ext_key', sa.Integer(), nullable=True),
    sa.Column('party_type', sa.String(length=128), nullable=True),
    sa.Column('province', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('village', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_email'), 'User', ['email'], unique=False)
    op.create_index(op.f('ix_User_full_name'), 'User', ['full_name'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('location', sa.VARCHAR(length=128), nullable=True),
    sa.Column('city', sa.VARCHAR(length=128), nullable=True),
    sa.Column('ext_key', sa.INTEGER(), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=128), nullable=True),
    sa.Column('party_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('province', sa.VARCHAR(length=128), nullable=True),
    sa.Column('village', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_User_full_name'), table_name='User')
    op.drop_index(op.f('ix_User_email'), table_name='User')
    op.drop_table('User')
    op.drop_index(op.f('ix_Customer_ext_key'), table_name='Customer')
    op.drop_table('Customer')
    # ### end Alembic commands ###
