"""empty message

Revision ID: a860f38d303f
Revises: 58b77835ca32
Create Date: 2020-04-17 20:31:05.329764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a860f38d303f'
down_revision = '58b77835ca32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
